# Generated by Django 5.0.14 on 2026-08-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='标识')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '文章分类',
                'verbose_name_plural': '文章分类',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='标识')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL 标识')),
                ('excerpt', models.CharField(blank=True, max_length=500, verbose_name='摘要')),
                ('cover_image', models.URLField(blank=True, verbose_name='封面图 URL')),
                ('content_html', models.TextField(blank=True, verbose_name='正文 HTML（UEditorPlus）')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已归档')], default='draft', max_length=16, verbose_name='状态')),
                ('is_featured', models.BooleanField(default=False, verbose_name='首页精选')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览量')),
                ('website_sections', models.JSONField(blank=True, default=list, verbose_name='首页板块')),
                ('section_order', models.IntegerField(default=0, verbose_name='板块内排序')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.category', verbose_name='分类')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='content.tag', verbose_name='标签')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', '-published_at'], name='content_art_status_9dc828_idx')],
            },
        ),
    ]
