# Generated by Django 5.0.14 on 2026-08-19 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_token', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='飞书文档 Token')),
                ('title', models.CharField(max_length=300, verbose_name='文档标题')),
                ('source', models.CharField(default='docx', max_length=16, verbose_name='链接类型')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_docs', to='content.article', verbose_name='关联文章')),
            ],
            options={
                'verbose_name': '飞书文档',
                'verbose_name_plural': '飞书文档',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeishuImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_token', models.CharField(db_index=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='文档标题')),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失败')], max_length=16, verbose_name='状态')),
                ('message', models.TextField(blank=True, verbose_name='说明')),
                ('image_count', models.IntegerField(default=0, verbose_name='转存图片数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feishu_import_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
            ],
            options={
                'verbose_name': '飞书导入日志',
                'verbose_name_plural': '飞书导入日志',
                'ordering': ['-created_at'],
            },
        ),
    ]
