# Generated by Django 5.0.14 on 2026-08-19 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_feishudocument_feishuimportlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeishuToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(verbose_name='user_access_token')),
                ('refresh_token', models.TextField(blank=True, verbose_name='refresh_token')),
                ('scope', models.TextField(blank=True, verbose_name='授权范围')),
                ('expires_at', models.DateTimeField(verbose_name='过期时间')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feishu_token', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '飞书用户令牌',
                'verbose_name_plural': '飞书用户令牌',
            },
        ),
    ]
