# Generated by Django 5.0.14 on 2026-08-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_feishutoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='feishutoken',
            name='refresh_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='refresh_token 过期时间'),
        ),
        migrations.AlterField(
            model_name='feishutoken',
            name='expires_at',
            field=models.DateTimeField(verbose_name='access_token 过期时间'),
        ),
    ]
