# Generated by Django 5.0.14 on 2026-08-22 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=32, unique=True, verbose_name='标识')),
                ('name', models.CharField(max_length=64, verbose_name='名称')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=16, verbose_name='图标（emoji）')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('staff_only', models.BooleanField(default=False, verbose_name='仅管理员发帖')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '论坛板块',
                'verbose_name_plural': '论坛板块',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='content_md',
            field=models.TextField(blank=True, verbose_name='回复 Markdown'),
        ),
        migrations.AddField(
            model_name='post',
            name='floor',
            field=models.PositiveIntegerField(default=0, verbose_name='楼层'),
        ),
        migrations.AddField(
            model_name='post',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AddField(
            model_name='topic',
            name='content_md',
            field=models.TextField(blank=True, verbose_name='正文 Markdown'),
        ),
        migrations.AddField(
            model_name='topic',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='摘要'),
        ),
        migrations.AddField(
            model_name='topic',
            name='last_reply_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='latest_replies', to=settings.AUTH_USER_MODEL, verbose_name='最后回复人'),
        ),
        migrations.AddField(
            model_name='topic',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='回复 HTML（服务端渲染）'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='content_html',
            field=models.TextField(blank=True, verbose_name='正文 HTML（服务端渲染）'),
        ),
        # node: CharField(choices) -> FK(Node)
        # PG 不支持 varchar 直接 ALTER 为 integer（无法自动 cast），必须 Remove+Add；
        # bbs 无任何写入口、表必为空，无数据丢失风险
        migrations.RemoveField(
            model_name='topic',
            name='node',
        ),
        migrations.AddField(
            model_name='topic',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='bbs.node', verbose_name='板块'),
        ),
    ]
