# Generated by Django 5.0.14 on 2026-08-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_node_post_content_md_post_floor_post_like_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='已删除'),
        ),
        migrations.AddField(
            model_name='post',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后编辑时间'),
        ),
        migrations.AddField(
            model_name='topic',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最后编辑时间'),
        ),
    ]
