# Generated by Django 5.0.14 on 2026-08-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='姓名')),
                ('role', models.CharField(blank=True, max_length=128, verbose_name='职务')),
                ('bio', models.TextField(blank=True, verbose_name='简介')),
                ('avatar_url', models.URLField(blank=True, verbose_name='头像 URL')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='在职/在册')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '团队成员',
                'verbose_name_plural': '团队成员',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(choices=[('home', '首页'), ('about', '关于我们'), ('philosophy', '理念')], max_length=32, unique=True, verbose_name='页面标识')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content_html', models.TextField(blank=True, verbose_name='内容 HTML')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pages', to=settings.AUTH_USER_MODEL, verbose_name='最后编辑人')),
            ],
            options={
                'verbose_name': '静态页',
                'verbose_name_plural': '静态页',
            },
        ),
    ]
