# Generated by Django 5.0.14 on 2026-08-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='slug',
            field=models.SlugField(choices=[('home', '首页'), ('about', '关于我们'), ('philosophy', '理念'), ('clover', '四叶草堂')], max_length=32, unique=True, verbose_name='页面标识'),
        ),
    ]
