# Generated by hand — 静态页管理扩展：状态/导航菜单字段 + 自由 slug。
# 数据迁移：存量 4 页置为已发布并补齐菜单信息（防止默认 draft 导致前台页面消失）。

from django.db import migrations, models

# slug → (菜单名称, 排序, 是否入导航)。
# 保持现有导航结构：花开中国 / 理念路径 / 关于我们(clover) + 固定"资讯分享"；
# about 原本不在导航，置为不入导航。
_MENU = {
    'home': ('花开中国', 0, True),
    'philosophy': ('理念路径', 1, True),
    'clover': ('关于我们', 2, True),
    'about': ('关于我们', 3, False),
}


def _fill_existing_pages(apps, schema_editor):
    from django.utils import timezone

    SitePage = apps.get_model('team', 'SitePage')
    now = timezone.now()
    for slug, (label, order, in_menu) in _MENU.items():
        SitePage.objects.filter(slug=slug).update(
            status='published',
            in_menu=in_menu,
            menu_label=label,
            menu_order=order,
            created_at=now,
        )
    # 兜底：其余存量页也补 created_at，避免 NULL 在排序时跨库不一致（SQLite/PG 对 NULL 排序不同）
    SitePage.objects.filter(created_at__isnull=True).update(created_at=now)


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_alter_sitepage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepage',
            name='slug',
            field=models.SlugField(max_length=64, unique=True, verbose_name='页面标识'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('archived', '已撤下')], default='draft', max_length=16, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='in_menu',
            field=models.BooleanField(default=False, verbose_name='显示在导航'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='menu_label',
            field=models.CharField(blank=True, max_length=64, verbose_name='菜单名称'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='menu_order',
            field=models.IntegerField(default=0, verbose_name='菜单排序'),
        ),
        migrations.AddField(
            model_name='sitepage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.RunPython(_fill_existing_pages, _noop),
        migrations.AlterModelOptions(
            name='sitepage',
            options={'ordering': ['menu_order', 'created_at', 'id'], 'verbose_name': '静态页', 'verbose_name_plural': '静态页'},
        ),
    ]
