# Generated by Django 5.0.14 on 2026-08-17 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='名称')),
                ('slug', models.SlugField(max_length=128, unique=True, verbose_name='标识')),
                ('status', models.CharField(choices=[('upcoming', '未开始'), ('ongoing', '进行中'), ('finished', '已结束')], default='upcoming', max_length=16, verbose_name='状态')),
                ('start_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('rules_html', models.TextField(blank=True, verbose_name='规则/说明 HTML')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '竞赛赛季',
                'verbose_name_plural': '竞赛赛季',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='作品标题')),
                ('content_html', models.TextField(blank=True, verbose_name='作品说明 HTML')),
                ('images', models.JSONField(blank=True, default=list, verbose_name='图片 URL 列表')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已退回')], default='pending', max_length=16, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.season', verbose_name='赛季')),
            ],
            options={
                'verbose_name': '参赛作品',
                'verbose_name_plural': '参赛作品',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(verbose_name='分数')),
                ('comment', models.TextField(blank=True, verbose_name='评语')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评分时间')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评委')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='contest.submission', verbose_name='作品')),
            ],
            options={
                'verbose_name': '评分',
                'verbose_name_plural': '评分',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='队伍名')),
                ('contact', models.CharField(blank=True, max_length=128, verbose_name='联系方式')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='报名时间')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='队长')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='成员')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='contest.season', verbose_name='赛季')),
            ],
            options={
                'verbose_name': '参赛队伍',
                'verbose_name_plural': '参赛队伍',
            },
        ),
        migrations.AddField(
            model_name='submission',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='contest.team', verbose_name='队伍'),
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(verbose_name='名次')),
                ('total_score', models.PositiveIntegerField(default=0, verbose_name='总分')),
                ('remark', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='公布时间')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='contest.season', verbose_name='赛季')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='contest.team', verbose_name='队伍')),
            ],
            options={
                'verbose_name': '排名',
                'verbose_name_plural': '排名',
                'ordering': ['rank'],
            },
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('submission', 'judge'), name='uniq_score_per_judge'),
        ),
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(fields=('season', 'name'), name='uniq_team_in_season'),
        ),
        migrations.AddConstraint(
            model_name='ranking',
            constraint=models.UniqueConstraint(fields=('season', 'team'), name='uniq_ranking_in_season'),
        ),
    ]
